service: bottender
app: messagine
org: suphero
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    environment:
      MESSENGER_PAGE_ID: ${param:MESSENGER_PAGE_ID}
      MESSENGER_ACCESS_TOKEN: ${param:MESSENGER_ACCESS_TOKEN}
      MESSENGER_APP_ID: ${param:MESSENGER_APP_ID}
      MESSENGER_APP_SECRET: ${param:MESSENGER_APP_SECRET}
      MESSENGER_VERIFY_TOKEN: ${param:MESSENGER_VERIFY_TOKEN}
      TELEGRAM_ACCESS_TOKEN: ${param:TELEGRAM_ACCESS_TOKEN}
